-- Tabelas ASP.NET Identity usadas pelo ERP SaaS no Supabase.
-- Execute depois de init-master-db-supabase.sql.
-- O projeto usa nomes de tabelas minúsculos, mas mantém os nomes padrão
-- das propriedades EF Core nas colunas.

CREATE TABLE IF NOT EXISTS public.users (
    "Id" UUID NOT NULL PRIMARY KEY,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0,
    "TenantId" UUID,
    "FirstName" VARCHAR(100) NOT NULL DEFAULT '',
    "LastName" VARCHAR(100) NOT NULL DEFAULT '',
    "Locale" VARCHAR(20) NOT NULL DEFAULT 'pt-BR',
    "Timezone" VARCHAR(100) NOT NULL DEFAULT 'America/Sao_Paulo',
    "AvatarUrl" TEXT,
    "Status" INTEGER NOT NULL DEFAULT 0,
    "EmailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "LastLogin" TIMESTAMP,
    "LastLoginIp" VARCHAR(45),
    "FailedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
    "TwoFactorSecret" TEXT,
    "TwoFactorRecoveryCodes" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.roles (
    "Id" UUID NOT NULL PRIMARY KEY,
    "Name" VARCHAR(256),
    "NormalizedName" VARCHAR(256),
    "ConcurrencyStamp" TEXT,
    "Description" TEXT,
    "IsSystem" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    "Id" UUID NOT NULL PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES public.users("Id") ON DELETE CASCADE,
    "RoleId" UUID NOT NULL REFERENCES public.roles("Id") ON DELETE CASCADE,
    CONSTRAINT uq_user_roles_user_id_role_id UNIQUE ("UserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS public.user_claims (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES public.users("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE IF NOT EXISTS public.user_logins (
    "Id" UUID NOT NULL PRIMARY KEY,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" UUID NOT NULL REFERENCES public.users("Id") ON DELETE CASCADE,
    CONSTRAINT uq_user_logins_provider_key UNIQUE ("LoginProvider", "ProviderKey")
);

CREATE TABLE IF NOT EXISTS public.role_claims (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" UUID NOT NULL REFERENCES public.roles("Id") ON DELETE CASCADE,
    "ClaimType" TEXT,
    "ClaimValue" TEXT
);

CREATE TABLE IF NOT EXISTS public.identity_user_tokens (
    "UserId" UUID NOT NULL REFERENCES public.users("Id") ON DELETE CASCADE,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT,
    CONSTRAINT pk_identity_user_tokens PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    "Id" UUID NOT NULL PRIMARY KEY,
    "RoleId" UUID NOT NULL REFERENCES public.roles("Id") ON DELETE CASCADE,
    "PermissionId" UUID NOT NULL REFERENCES public.permissions(id) ON DELETE CASCADE,
    CONSTRAINT uq_role_permissions_role_id_permission_id UNIQUE ("RoleId", "PermissionId")
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_normalized_user_name
    ON public.users("NormalizedUserName")
    WHERE "NormalizedUserName" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_normalized_email
    ON public.users("NormalizedEmail")
    WHERE "NormalizedEmail" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email
    ON public.users("Email")
    WHERE "Email" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username
    ON public.users("UserName")
    WHERE "UserName" IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_user_claims_user_id
    ON public.user_claims("UserId");

CREATE INDEX IF NOT EXISTS ix_role_claims_role_id
    ON public.role_claims("RoleId");

CREATE INDEX IF NOT EXISTS ix_user_roles_role_id
    ON public.user_roles("RoleId");

CREATE INDEX IF NOT EXISTS ix_role_permissions_role_id
    ON public.role_permissions("RoleId");

CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id
    ON public.role_permissions("PermissionId");

INSERT INTO public.roles ("Id", "Name", "NormalizedName", "Description", "IsSystem", "IsActive")
VALUES (
    '770e8400-e29b-41d4-a716-446655440000',
    'Admin',
    'ADMIN',
    'Administrador do sistema',
    TRUE,
    TRUE
)
ON CONFLICT ("Id") DO NOTHING;
